### PR TITLE
Make sure HF download metrics work

### PR DESCRIPTION
**Pull request by NielsRogge**
Dear authors,

I noticed your awesome repository trending on X. I see you already leverage `hf_hub_download`, however all checkpoints are present in a [single repository](https://huggingface.co/lpiccinelli/UniDepth), which means download metrics won't work. 😞 

This PR resolves that by showcasing the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class, which is a minimal class that allows to easily add functionalities like `from_pretrained`, `save_pretrained`, and `push_to_hub` to any custom `nn.Module` (without the need to rely on Torch hub or define your own `from_pretrained`). 

Similar to models in the Transformers/Diffusers library, it allows to push and reload models in the format of `safetensors` (for the weights) and a `config.json` (for the model's configuration). It also creates an automated model card, along with tags for better discoverability of your models. Usage is as follows:

```
from unidepth.models import UniDepthV1HF

model = UniDepthV1HF.from_pretrained("nielsr/unidepth-v1-convnext-large")
```
The corresponding model is here for now: https://huggingface.co/nielsr/unidepth-v1-convnext-large, but I could transfer it (along with the ViT-large checkpoint) to your organization.

Here's a [notebook](https://colab.research.google.com/drive/1B1Ej_GbKihb5_xE_x50Z_B3XyM0DNT_-?usp=sharing) regarding how I did that :)

Would you be interested in this integration?

Kind regards,

Niels
ML @ HF

### CODE REVIEW

**Comment by lpiccinelli-eth** [comment]
Thank you for your contribution! 

I will review and test it asap

**Comment by NielsRogge** [comment]
Thanks! Let me know if you need any help. Would be great if you could try it out to upload the various checkpoints to the hub!

**Comment by lpiccinelli-eth** [comment]
LGTM

**Comment by NielsRogge** [comment]
Thanks for merging my PR! 🤗 

Would you be up for pushing the various checkpoints to the hub as shown in [this notebook](https://colab.research.google.com/drive/1B1Ej_GbKihb5_xE_x50Z_B3XyM0DNT_-?usp=sharing)?

This way you'll get download metrics for your various checkpoints. Also feel free to update the README/sample code so that people can start using them!

**Comment by lpiccinelli-eth** [comment]
We tested them and pushed the checkpoints on the hub as you suggested, now we are updating the README, thanks again!

**Comment by lpiccinelli-eth** [comment]
That would be really cool for users, we are releasing version 2 soon (faster, more flexible architecture and larger and corrected dataset), that would be nice to be integrated in transformers!

**Comment by lpiccinelli-eth** [comment]
Thank you for pointing this out and yes, you are right, my `huggingface_hub` was outdated, now I updated it and amended the requirements, too, thanks!

**Comment by NielsRogge** [comment]
Great! Btw @wauplin (maintainer of `huggingface_hub`) pointed out that we could merge both classes into one.

The reason I created a separate `UniDepthHF` class was only because there was already a `from_pretrained` method defined. 

Basically there's no need for torch hub anymore, since I see that even the torch hub code loads the checkpoints from the hub 😅 (but without download metrics working due to use of `hf_hub_download`).

Do you want me to submit a PR to simplify things?

**Comment by lpiccinelli-eth** [comment]
If you want to open a PR to clean it,  I appreciate it. I would like to keep `hubconf.py` still, just in case someone likes it more for some reasons :sweat_smile:

**Comment by NielsRogge** [comment]
Looks like download metrics are working 🙌 

Btw, those model cards look pretty empty.. 😉 

Screenshot 2024-04-12 at 21 34 45

**Comment by NielsRogge** [comment]
Opened a PR to simplify things: #14

**Pull request merged**
